[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.15.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Functions directory
[functions]
  directory = "netlify/functions"

# Redirect for single blog post API
[[redirects]]
  from = "/api/posts/:slug"
  to = "/.netlify/functions/get-post/:slug"
  status = 200
  force = false

# Redirect for all blog posts API
[[redirects]]
  from = "/api/posts"
  to = "/.netlify/functions/get-posts"
  status = 200
  force = false

# Direct call to HTML-generating Netlify function for blog posts
[[redirects]]
  from = "/blog/:slug"
  to = "/.netlify/functions/blog-post-html/:slug"
  status = 200
  force = true

# Fallback for blog routes - ensure we serve the SPA for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 